### PR TITLE
Upgrade to nim-1.4.0

### PR DESCRIPTION
**Pull request by pb-cdunn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pb-cdunn** [comment]
https://github.com/conda-forge/nim-feedstock/issues/4

**Comment by pb-cdunn** [comment]
@conda-forge-admin, please rerender

**Comment by pb-cdunn** [comment]
I guess we didn't really need to re-render, but it worked.

**Review by mbargull — COMMENTED** [review]
LGTM

**Pull request merged**
