### PR TITLE
Updating version to 1.4.8 and adding sha256sum

### PR DESCRIPTION
**Pull request by btcross26**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by btcross26** [comment]
@conda-forge-admin, please rerender

**Comment by pb-cdunn** [comment]
Are you certain this actually works? Can you point me to a recipe that uses this for compilation? What I had pushed worked me, but this does not.

* https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/48896/workflows/56e6689c-f9c5-42ae-8dc5-bf599e68493b/jobs/159945
* https://github.com/bioconda/bioconda-recipes/pull/29294

```
20:26:47 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/subprocess.py", line 1447, in _execute_child
20:26:47 BIOCONDA INFO (OUT)     restore_signals, start_new_session, preexec_fn)
20:26:47 BIOCONDA INFO (OUT) OSError: [Errno 12] Cannot allocate memory
```

**Comment by pb-cdunn** [comment]
This might be the problem:

* https://github.com/conda-forge/nim-feedstock/pull/6
* https://github.com/nim-lang/Nim/pull/15908

**conda-forge-linter** removed `recipe/0001-gh-15042--Increase-buffer-size-for-readlink-to-1024.patch`, which was added to `Nim/devel` but maybe not the releases ...

... Nope, that's not it.
```
9fb713cf2 Fix a problem for long symlinks in conda (#15908) [backport]
```
That is under the `v1.4.8` tag.

I'd like to see how a recipe uses this feedstock. Maybe I am doing something wrong.

**Comment by btcross26** [comment]
Definitely works for me on my Linux machine. I will test on MacOS later.

## example.nim
echo "Hello World!"

## command line
```bash
$ conda create -n nim_test_148 -c conda-forge nim=1.4.8
$ conda activate nim_test_148
$ nim c --run example.nim
```
##
output
```bash
$ Hello World!
```
`which nim` gives me `/home/ben/anaconda3/envs/nim_148_test/bin/nim`
`nim --version` gives:

```bash
Nim Compiler Version 1.4.8 [Linux: amd64]
Compiled at 2021-05-31
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: fbb0ed497322722bf7f0aa01f51a9edbeaf74efa
active boot switches: -d:release
```

**Comment by cdunn2001** [comment]
Yes, nim works fine as a conda-installed executable, but I need it to work as a *compiler*, so I can build nim code in Bioconda. Either something changed in the Nim source, or something is a problem in the changes to the feedstock.

Here is an example of a Bioconda recipe:

* https://github.com/bioconda/bioconda-recipes/tree/master/recipes/pb-falconc

Look at `meta.yaml`. That's a Bioconda "recipe".
```yaml
requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - nim
    - rsync
```
That's the typical use-case within **Bioconda**.

The servers that the build runs on might be too limited in memory for the way Nim is used, but they are enough to build normal C++ code.

**Comment by btcross26** [comment]
I do use it as a compiler above - I just have the added --run flag to go ahead and execute the program. Looking at your falconc repo makefile, are you sure that the out-of-memory error is not occuring during the `rsync` step? The message you have above is kind of cryptic. Just spitballing here. A quick google search suggests `rsync` can cause out of memory when lots of files are downloaded, even when the files are not large. The solution offered is to include the `--no-inc-recursive` flag.

**Comment by cdunn2001** [comment]
```sh
/usr/bin/time -l make rsync

sent 102,978 bytes  received 408 bytes  206,772.00 bytes/sec
total size is 101,821  speedup is 0.98
        3.38 real         0.34 user         0.67 sys
           117047296  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               15228  page reclaims
                5486  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                 536  messages sent
                 522  messages received
                  38  signals received
                5167  voluntary context switches
                1518  involuntary context switches
            28461338  instructions retired
            16236665  cycles elapsed
             1229680  peak memory footprint
```
That's on OSX. It's a good theory, but I doubt it's the problem. The files being rsync'd are just not very big.

**Comment by cdunn2001** [comment]
I'm trying to use this Nim directly, in a fresh conda environment on OSX:
```sh
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
```
I've updated xtools and reinstalled miniconda. Same problem. Any ideas?

**Comment by cdunn2001** [comment]
Interesting. I was not able to use the `clang++` that is in Conda, but I managed to use a local compiler with `nim c --cc:llvm-gcc`.

I guess we could try something like that in the bioconda-recipe. But I think I'm better off just installing a prebuilt binary instead.

**Pull request merged**
